### ISSUE TITLE
Convergence speed & final performance/perplexity

### ISSUE THREAD

**Issue by soloice** [YisenWang/LightRNN-NIPS2016-Tensorflow_code#3]
Hi, Wang,

I'm wondering how your LightRNN code behaves on ptb dataset?
I used your previous code and found it converges quite slow (compared to TensorFlow's PTB language model example) and ppl is quite large (>200 after 20 epoches). 
Am I getting it wrong?

**Comment by soloice** [comment]
And may I ask why you cleared the repo?
Is it a copyright issue? Or there exists severe bugs in code? Or some other reason?
I need more information to decide if I should keep working on LightRNN, so could you please kindly share your experience with this model? Any advice is welcome. Thank you in advance.

**Comment by kaierlong** [comment]
@soloice I just read the old code and the official code from MS [LightRNN](https://github.com/Microsoft/CNTK/tree/master/Examples/Text/LightRNN). They are both different from the paper [LightRNN: Memory and Computation-Efficient Recurrent Neural Networks](https://arxiv.org/abs/1610.09893). So I want to email to the author for confirming the results.

**Comment by soloice** [comment]
@kaierlong Thanks for your kind reply. Looking forward to your good news.

**Comment by fengerchui** [comment]
Hi, wang,
How about the author's reply email.
Now I meet the same problem, I code as that paper, but the result is not satisfied.

**Comment by YisenWang** [comment]
The code clearance is due to the company restrict. I no longer maintain this repo.
